function New-NCUserRole {
<#
.SYNOPSIS
    Adds a new user role to MSP N-central.

.PARAMETER Name


.PARAMETER Description


.PARAMETER CustomerId


.PARAMETER PermissionId
    

.PARAMETER UserId
    

.EXAMPLE
    
#>

[CmdletBinding()]
Param (
    [Parameter(Mandatory=$true)]
    [ValidateLength(1,256)]
    [string]
    $Name,

    [Parameter(Mandatory=$true)]
    [string]
    $Description,

    [Parameter(Mandatory=$true)]
    [uint64]
    $CustomerId,

    [Parameter(Mandatory=$true)]
    [string]
    $PermissionId,

    [Parameter(Mandatory=$false)]
    [string]
    $UserId
)

    <#
    Mandatory - (Key) roleName - (Value) Name for the new user role. Maximum of 256 characters.
Mandatory - (Key) roleDescription - (Value) Description of the new role.
Mandatory - (Key) customerID - (Value) The customerID of the site/customer/SO that the user role is associated with.
Mandatory - (Key) permissionID - (Value) permission IDs for the new role.
(Key) userID - (Value) The userIDs of the users associated with the role.
    
permissions:

[CUSTOMER_ORGANIZATION_ALL, USERS_ALL, ALL_DEVICE_VIEW, DEVICE_RULES_ALL, DEVICE_FILTERS_ALL,
DEVICE_DOWNTIME_ALL, AUDIT_TRAIL_VIEW, DASHBOARDS_ALL, PATCH_APPROVAL_ALL, PATCH_CONFIGURATION_ALL,
SCHEDULED_TASKS_ALL, AUTOMATION_MANAGER_ALL, SCHEDULED_TASKS_FILE_REPOSITORY_ALL,
SECURITY_MANAGER_PROFILES_ALL, SECURITY_MANAGER_QUARANTINE_ALL, SECURITY_MANAGER_EVENTS_ALL,
SECURITY_MANAGER_EXCLUSIONS_ALL, SECURITY_MANAGER_UPDATE_SERVERS_ALL, REPORT_MANAGER_ADMINISTRATION_ALL,
REPORT_MANAGER_ALL, NCENTRAL_REPORTS_ALL, NCENTRAL_REPORTS_CONTROL_ALL, DISCOVERY_JOBS_ALL,
MY_LINKS_ALL, HELP_RESOURCES_VIEW, RSS_VIEW, THIRD_PARTY_SOFTWARE_DOWNLOAD_ALL,
NCENTRAL_UPGRADE_FAIL_MESSAGE, NCENTRAL_BACKUP_ALL, NCENTRAL_DEFAULTS_ALL, NCENTRAL_ADMIN_TOOLS_ALL,
NCENTRAL_CERTIFICATE_ALL, BACKUP_MANAGER_PROFILES_ALL, BRANDING_ALL, CUSTOM_PROPERTIES_ADMIN,
APPLICATION_COMPLIANCE_ALL, LICENSE_COMPLIANCE_ALL, NOTIFICATION_TEMPLATES_ALL,
NOTIFICATION_PROFILES_ALL, NOTIFICATION_GLOBAL_CONTROL_ALL, NOTIFICATIONS_SOFTWARE_UPGRADES_ALL,
ACTIVE_ISSUES_VIEW, SERVICE_CONTROL_ALL, SERVICE_ALL, SERVICE_TEMPLATES_ALL, CUSTOM_SERVICE_ALL,
ALERTS_ACKNOWLEDGE_ALL, PSA_INTEGRATION_ALL, TICKETING_ALL, DIRECT_SUPPORT_APPLICATIONS_ALL,
DIRECT_SUPPORT_TASK_EXECUTION_ALL, DIRECT_SUPPORT_COMMAND_PROMPT_ALL,
DIRECT_SUPPORT_DOMAIN_USER_MANAGEMENT_ALL, DIRECT_SUPPORT_FILE_SYSTEM_ALL,
DIRECT_SUPPORT_POWER_MANAGEMENT_ALL, DIRECT_SUPPORT_PRINTERS_ALL, DIRECT_SUPPORT_PROCESSES_ALL,
DIRECT_SUPPORT_REGISTRY_ALL, DIRECT_SUPPORT_SERVICES_ALL, DIRECT_SUPPORT_STARTUP_APPLICATIONS_ALL,
REMOTE_CONTROL_SETTINGS_ALL, REMOTE_CONTROL_CUSTOM_ALL, REMOTE_CONTROL_MSP_CONNECT_ALL,
REMOTE_CONTROL_REMOTE_DESKTOP_ALL, REMOTE_CONTROL_WEB_ALL, PROPERTY_LOCK_ALL,
REMOTE_CONTROL_TEAMVIEWER_ALL, REMOTE_CONTROL_SSH_ALL, REMOTE_CONTROL_TELNET_ALL,
LAN_DEVICE_SETTINGS_ALL, LAN_DEVICE_MANAGEMENT_ALL, MOBILE_DEVICE_SETTINGS_ALL,
MOBILE_DEVICE_MANAGEMENT_ALL, SAAS_DEVICE_SETTINGS_ALL, SAAS_DEVICE_MANAGEMENT_ALL,
MSP_BACKUP_PROFILES_ALL, MSP_BACKUP_DASHBOARD_ALL, MSP_BACKUP_PASSPHRASE_VIEW, NETPATH_ALL,
NCENTRAL_REPORTS_DATA_EXPORT, CUSTOM_PROPERTIES_USE, NCENTRAL_INTEGRATION_MANAGEMENT_ALL,
INTEGRATION_SENTINELONE_CONFIG_ALL, LIVECHAT_ALL,
SECURITY_MANAGER_DISK_ENCRYPTION_RECOVERY_KEY_REPORT_ALL, TOPOLOGY_JOBS_VIEW, TOPOLOGY_JOBS_ALL,
SECURITY_MANAGER_DISK_ENCRYPTION_RECOVERY_KEY_ALL]



#>

    
}